apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pomodoro-volume-claim

spec:
  #storageClassName: hostpath
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
---
#apiVersion: v1
#kind: PersistentVolume

#metadata:
#  name: local-volume
#  labels:
#    type: local

#spec:
#  storageClassName: hostpath
#  capacity:
#    storage: 10Gi

#  accessModes:
#    - ReadWriteOnce

#  hostPath:
#    path: /mnt/data