apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
     labels:
       app: authorization
    spec:
      containers:
        - image: authorization:0.1
          imagePullPolicy: Never
          name: authorization
          ports:
            - containerPort: 80
          #volumeMounts:
           # - name: mssqldb
           #   mountPath: /var/opt/mssql
     # volumes:
      #- name: mssqldb
        #persistentVolumeClaim:
         #claimName: local-volume-claim
