apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
     labels:
       app: authorization
    spec:
      containers:
        - image: authorization:0.1
          imagePullPolicy: Never
          name: authorization
          ports:
            - containerPort: 80
