apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: authorization-destination
spec:
  host: authorization-service
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 10
      interval: 10s
      baseEjectionTime: 30s
      maxEjectionPercent: 80