apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
     labels:
       app: testing
    spec:
      containers:
        - image: testing:0.1
          imagePullPolicy: Never
          name: testing
          ports:
            - containerPort: 80
