apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssqldb-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomodoro-db

  minReadySeconds: 5
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: pomodoro-db

    spec:
      containers:
        - name: pomodoro-database
          image: microsoft/mssql-server-linux
          ports:
            - containerPort: 1433

          env:
            - name: "ACCEPT_EULA"
              value: "Y"

            - name: "SA_PASSWORD"
              value: "Password_123"

            - name: "MSSQL_PID"
              value: "Express"
          volumeMounts:
            - name: mssqldb
              mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
         claimName: pomodoro-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssqldb
spec:
  selector:
    app: pomodoro-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort
