apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
     labels:
       app: tasks
    spec:
      containers:
        - image: tasks:0.1
          imagePullPolicy: Never
          name: tasks
          ports:
            - containerPort: 80
